name: Deploy to Portainer via Tailscale (Reusable)

on:
  workflow_call:
    inputs:
      portainer_ip:
        description: "IP do servidor Portainer na rede Tailscale"
        required: true
        type: string
      webhook_token:
        description: "Token do webhook do Portainer"
        required: true
        type: string
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: "1Password Service Account Token"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Credentials
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TAILSCALE_AUTHKEY: op://6jujnoj7fa7dqx5ngjzy2itjfi/qvrc5hntqdqptlp7pc33h5fcsu/senha

      - name: Print masked secret
        run: 'echo "Secret: ${{ env.TAILSCALE_AUTHKEY }}"'

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --ssh --auth-key=${{ env.TAILSCALE_AUTHKEY }}

      - name: Call Portainer Webhook via Tailscale
        env:
          PORTAINER_WEBHOOK_URL: "https://${{ inputs.portainer_ip }}:9443/api/stacks/webhooks/${{ inputs.webhook_token }}"
        run: |
          echo "Forçando resolução de DNS para o IP do Portainer na rede Tailscale..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST $PORTAINER_WEBHOOK_URL --insecure)

          if [ "$response" -ne 204 ]; then
            echo "Deployment failed with status code $response"
            exit 1
          else
            echo "Deployment triggered successfully with status code $response"
          fi

      - name: Disconnect from Tailscale
        run: sudo tailscale logout
